#
# Copyright (C) 2024 Keith Scott <keithlscott@gmail.com>
# GNU Public License Version 3, 29 June 2007
#


#
# Set up the 'production' container.
#
FROM ubuntu

RUN apt -y update
RUN apt -y install iproute2 iputils-ping tcpdump collectd vim psmisc jq
RUN apt -y install python3
RUN apt -y install python3-pip
RUN pip install --break-system-packages statsd-tags influxdb_client

#
# Copy files from etc to the container without replacing the
# entire /etc directory.  Files already present will be
# overwritten.
#
COPY ./etc/. /etc
COPY ./container_start.sh /netem/bin/container_start.sh

CMD ["/bin/bash", "/netem/bin/container_start.sh"]

